# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rwr < Formula
  desc "Rinse, Wash, Repeat (RWR) - Configuration Management Tool"
  homepage "https://github.com/fynxlabs/rwr"
  version "0.1.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FynxLabs/rwr/releases/download/v0.1.12/rwr_Darwin_x86_64.tar.gz"
      sha256 "003f335a1e3b22606cadb3e999b43277ca7ecd5bb2aadc2b3a53c62f4950e1e2"

      def install
        bin.install "rwr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FynxLabs/rwr/releases/download/v0.1.12/rwr_Darwin_arm64.tar.gz"
      sha256 "08a14a4a718737a54f25b47c8caf62b33facbc4e8f8fd2c08d387c67c875c783"

      def install
        bin.install "rwr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FynxLabs/rwr/releases/download/v0.1.12/rwr_Linux_x86_64.tar.gz"
        sha256 "fc82b9238331f7b40d3f7ed2e8993f2774d6d9a6d0a7e50d0dc7225ea52f51f2"

        def install
          bin.install "rwr"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/FynxLabs/rwr/releases/download/v0.1.12/rwr_Linux_armv7.tar.gz"
        sha256 "9515eedd4ef364f7261fc859c6bd37d7ea8878039826f66682ce9f68ea514c6b"

        def install
          bin.install "rwr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FynxLabs/rwr/releases/download/v0.1.12/rwr_Linux_arm64.tar.gz"
        sha256 "df98cd56cb460da6c3e3696d6f0a7916450c2c103ac4b0348936dc4aa723c259"

        def install
          bin.install "rwr"
        end
      end
    end
  end
end
