# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rwr < Formula
  desc "Rinse, Wash, Repeat (RWR) - Configuration Management Tool"
  homepage "https://github.com/fynxlabs/rwr"
  version "0.0.1-alpha"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/FynxLabs/rwr/releases/download/v0.0.1-alpha/rwr_Darwin_x86_64.tar.gz"
      sha256 "6ca82490bc514ced8cd6a1c1173b396e161d2539dede629d7ea1ab0eab0e63f7"

      def install
        bin.install "rwr"
      end
    end
    on_arm do
      url "https://github.com/FynxLabs/rwr/releases/download/v0.0.1-alpha/rwr_Darwin_arm64.tar.gz"
      sha256 "785f2becb0cc5def7e7d0275210984b0fe41eb31a9c14b1497a9c92d29a2c468"

      def install
        bin.install "rwr"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FynxLabs/rwr/releases/download/v0.0.1-alpha/rwr_Linux_x86_64.tar.gz"
        sha256 "947129f36478b0f9f620eb741aa73d3421a9cb0040be700f24efc91ebe6fae67"

        def install
          bin.install "rwr"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/FynxLabs/rwr/releases/download/v0.0.1-alpha/rwr_Linux_armv7.tar.gz"
        sha256 "c052d47bf84baf86df03e00f1c8661388165300eebed62ebd7d5964c9a7c3c5a"

        def install
          bin.install "rwr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FynxLabs/rwr/releases/download/v0.0.1-alpha/rwr_Linux_arm64.tar.gz"
        sha256 "d9da9ac0dd3095128a398348c90a39de0edaeab422f98f41d8f9ef44c01fc48e"

        def install
          bin.install "rwr"
        end
      end
    end
  end
end
